version: '3.1'
# en el tutorial es postgress 15.3, container_name: codrr
services:
   codrr_pg:
      image: postgres:15.3
      container_name: nest_amazon_ec2
      restart: always
      environment:
        POSTGRES_DB: nest_amazon_ec2
        POSTGRES_USER: jduser
        POSTGRES_PASSWORD: secret1234
      volumes:
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
       - 5432:5432

